# Generated by Django 5.0 on 2023-12-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlasticolApp', '0003_remove_login_regdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='civilians',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
