# Generated by Django 5.0 on 2024-01-30 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlasticolApp', '0006_suggestions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('note', models.CharField(max_length=300)),
                ('date', models.DateField(auto_now=True)),
                ('status', models.CharField(default='Collected', max_length=100)),
                ('civil_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlasticolApp.civilians')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlasticolApp.staff')),
            ],
        ),
    ]
