# Generated by Django 5.0 on 2024-01-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlasticolApp', '0008_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='capacity',
            field=models.IntegerField(default=500),
        ),
    ]
