# Generated by Django 5.0 on 2024-02-01 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlasticolApp', '0009_alter_storage_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='civilians',
            name='houseno',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='civilians',
            name='members',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
