# Generated by Django 5.0 on 2024-02-01 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlasticolApp', '0010_civilians_houseno_civilians_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('image', models.FileField(upload_to='')),
                ('status', models.CharField(default='Filed', max_length=100)),
                ('civilId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlasticolApp.civilians')),
            ],
        ),
    ]
