# Generated by Django 5.0 on 2024-02-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlasticolApp', '0011_complaints'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
