# Generated by Django 5.0 on 2024-02-02 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlasticolApp', '0012_complaints_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='civilians',
            old_name='members',
            new_name='ward',
        ),
    ]
